[package]
name = "agda-tree"
version = "0.2.2"
edition = "2021"
description = "A build tool for *.lagda.tree format"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
html_parser = "0.7.0"
